[features]
seeds = false
skip-lint = false
[programs.devnet]
otaku = "2amGSCnMV6RzJothNXnskJLcJoEykXNfgNssFbtwRkVL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/0xAckerman/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
